version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:80"  # Expose backend on port 8080
    volumes:
      - ./backend/src:/var/www/html/src
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Serve the React app on port 3000
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: mysql:5.6  # Use MySQL 5.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Use port 3307 on the host to avoid conflicts with local MySQL
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
